apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-gateway
  labels:
    app.kubernetes.io/name: kuber-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: kuber-gateway
  template:
    metadata:
      name: kuber-gateway
      labels:
        app.kubernetes.io/name: kuber-gateway
        app.kubernetes.io/instance: kuber-gateway
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: gateway
        app.kubernetes.io/part-of: kubers
        app.kubernetes.io/managed-by: kuber
    spec:
      containers:
        - name: kuber-gateway
          image: kuber/kuber-gateway:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Xmx256m
            - name: TZ
              value: Asia/Shanghai
            - name: SPRING_CONFIG_LOCATION
              value: 'optional:classpath:/,optional:classpath:/config/,optional:file:./,optional:file:./config/'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
#          livenessProbe:
#            timeoutSeconds: 5
#            periodSeconds: 10
#            httpGet:
#              port: 8761
#              path: /actuator/health/liveness
#          readinessProbe:
#            timeoutSeconds: 5
#            periodSeconds: 10
#            httpGet:
#              port: 8761
#              path: /actuator/health/readiness
#          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "250m"
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
#          lifecycle:
#            preStop:
#              exec:
#                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /application.yml
              name: config
              subPath: application.yml
      volumes:
        - name: config
          configMap:
            name: kuber-gateway
            items:
              - key: application.yml
                path: application.yml
      restartPolicy: Always

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-gateway
data:
  application.yml: |
    server.port: 9000
    spring:
      application:
        name: kuber-gateway
      cloud:
        gateway:
          routes:
            - id: kuber-controller
              uri: http://kuber-controller.default.svc:9999
              predicates:
                - Path=/**
    eureka:
      instance:
        prefer-ip-address: true
      client:
        service-url:
          defaultZone: http://kuber-discovery-0.kuber-discovery.default.svc:8761/eureka/,http://kuber-discovery-1.kuber-discovery.default.svc:8761/eureka/,http://kuber-discovery-2.kuber-discovery.default.svc:8761/eureka/
            

---

apiVersion: v1
kind: Service
metadata:
  name: kuber-gateway
spec:
  selector:
    app.kubernetes.io/name: kuber-gateway
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
