kind: Namespace
apiVersion: v1
metadata:
  name: kube-logging

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-logging
spec:
  selector:
    app.kubernetes.io/name: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: kube-logging
  labels:
    app.kubernetes.io/name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
          env:
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
